[versions]
agp = "8.13.1"
kotlin = "2.2.21"
androidTools = "31.13.1"
ksp = "2.2.20-2.0.4"
hilt = "2.57.2"
hilt-navigation-compose = "1.3.0"
kotlin-serialization = "2.2.21"

#network
retrofit = "2.9.0"
okhttp = "4.10.0"
moshi = "1.12.0"
eithernet = "1.9.0" # had to lower to 1.x.x since 2.x.x has breaking changes with ApiResultConverterFactory and ApiResultCallAdapterFactory

#room
room = "2.8.3"

#logging
timber = "5.0.1"

#testing
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinx-coroutines-test = "1.10.2"
mockk = "1.14.6"
turbine = "1.2.1"
instantiator = "1.0.0"
testRunner = "1.7.0"
mockwebserver = "5.3.0"
mockito = "5.20.0"
mockitoAndroid = "6.1.0"
testng = "7.11.0"
androidx-arch-core-testing = "2.2.0"
jacocoVersion = "0.8.13"

coreKtx = "1.17.0"
lifecycleRuntimeKtx = "2.9.4"
espressoCore = "3.7.0"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
constraintlayout = "1.1.1"
iconsExtended = "1.7.8"

appcompat = "1.7.1"
material = "1.13.0"
accompanist = "0.32.0"
playServicesLocation = "21.3.0"
uiToolingPreview = "1.10.2"
uiTooling = "1.10.2"
coil = "3.0.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanist" }

#compose ui
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout" }
androidx-compose-material-icons = {group = "androidx.compose.material", name = "material-icons-extended", version.ref = "iconsExtended"}


androidx-compose-material3-adaptive-navigation-suite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }

#coil
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation-compose" }

#network
retrofit-core = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }


kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

slack-eithernet = { module = "com.slack.eithernet:eithernet", version.ref = "eithernet" }

#room
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-rxjava2 = { group = "androidx.room", name = "room-rxjava2", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# testing
testing-junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-testing-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines-test" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
testing-mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
testing-turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
testng-testng = { module = "org.testng:testng", version.ref = "testng" }
testing-instantiator = { module = "com.hannesdorfmann.instantiator:instantiator", version.ref = "instantiator" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "testRunner" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitVersion" }
testing-mock-webserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockwebserver" }
testing-mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
testing-mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoAndroid" }
androidx-arch-core-testing = { module = "androidx.arch.core:core-testing", version.ref = "androidx-arch-core-testing" }
#junit = { group = "junit", name = "junit", version.ref = "junitJunit" }

#logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

#static analysis
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
lint-api = { group = "com.android.tools.lint", name = "lint-api", version.ref = "androidTools" }
lint-checks = { group = "com.android.tools.lint", name = "lint-checks", version.ref = "androidTools" }
lint-tests = { group = "com.android.tools.lint", name = "lint-tests", version.ref = "androidTools" }


# Dependencies of the included build-logic
android-gradle-api-plugin = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
hilt-gradle-plugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
room-gradle-plugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin-serialization" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
androidx-room = { id = "androidx.room", version.ref = "room" }
jacoco-report-aggregation = { id = "jacoco-report-aggregation" }

#Plugins defined by this project
minipokedex-android-application = { id = "convention.android.application" }
minipokedex-android-library = { id = "convention.android.library" }
minipokedex-android-application-compose = { id = "convention.android.application.compose" }
minipokedex-android-library-compose = { id = "convention.android.library.compose" }
minipokedex-android-application-test = { id = "convention.android.application.test" }
minipokedex-android-library-test = { id = "convention.android.library.test" }
minipokedex-kotlin-jvm-unit-test = { id = "convention.kotlin.jvm.unit.test" }
minipokedex-hilt = { id = "convention.hilt" }
minipokedex-network = { id = "convention.network" }
minipokedex-room = { id = "convention.room" }
minipokedex-android-lint = { id = "convention.android.lint" }
minipokedex-android-library-jacoco = {id = "convention.android.library.jacoco"}
minipokedex-android-application-jacoco = {id = "convention.android.application.jacoco"}
